### ISSUE TITLE
Workspace config format

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/dsm#9]
We would like each workspace to have sensible defaults when working in `dsm` but also provide ways to configure what `dsm` can do with a workspace. In particular, this config format should:

- Allow users to describe the tasks that the workspace can perform, both coming from npm tasks or custom tasks written in Node.js or another runner
- Allow users to describe the files that a workspace uses as source files for tasks like build, test, lint, etc.
- Allow users to describe the files that a workspace outputs for tasks like build
  - This helps with incremental build caching and auto-clean for workspaces
- Allow users to describe the versioning scheme for release workflows, schemes could include:
  - pre-release only
  - Conventional commits
  - Custom

**Comment by joshblack** [comment]
Idea based on GitHub Action workflow syntax:

```yml
workspace:
  name: My workspace
  tasks:
    build:
      - uses: builtin/cache
        with: [es, lib]
      - uses: builtin/source
        with: src
        ignore:
          - **/__tests__/**
      - uses: builtin/npm-scripts
  release:
    strategy: conventional-commits
```
